# 无穷乘积
## 无穷乘积的定义
设$\displaystyle p_1,p_2,...,p_n,..,(p_n\neq0)$是无穷可列个（一共有无穷个，但是能把它们都列出来）实数，我们称它们的“积”
$$
p_1 \cdot p_2 \cdot \ldots \cdot p_n \cdot \ldots
$$

为无穷乘积，记为$\displaystyle \prod_{n=1}^{\infty}p_n$,其中$p_n$称为**无穷乘积的通项**或**一般项**。

::: {.callout-tip}
这里的介绍中要求$\displaystyle p_n\neq0$，因为如果有一个元素为0的话，就没有研究的必要了。
:::

无穷乘积$\displaystyle \prod_{n=1}^{\infty}p_n$的“**部分积数列**”$\{P_n\}$:

$$
\begin{align}
P_1 &= p_1,  \\
P_2 &= p_1 \cdot p_2 \\
P_3 &= p_1 \cdot p_2 \cdot p_3 \\ 
\cdots & \cdots \cdots \cdots \cdots  \\
P_n &= p_1 \cdot p_2 \cdot \cdots \cdot p_n = \prod_{k=1}^{n}p_k, \\
\cdots & \cdots \cdots \cdots \cdots
\end{align}
$$

这里的级数让我想到了之前学过无穷数列，关于无穷数列我们关心的是在无穷远处它会变成什么样子，那对于级数我们关心的是这一组数据（虽然有无穷个）相乘的结果，可能还有它们相加的结果。

部分积数列是一个数列，这很重要，虽然每个元素可能由很多个项去相乘得到的。这个数列的项数是无穷个，因为无穷乘积的部分乘积叫部分积数列，而无穷乘积的项是无限的，也就意味着部分积数列可以无限的延展下去。

### 定义
::: {#def-无穷乘积收敛与发散}
如果部分积数列$\displaystyle \{P_n\}$ 收敛于一个非零的有限数$\displaystyle P$，则称无穷乘积$\displaystyle \prod_{n=1}^{\infty}p_n$收敛，且称$\displaystyle P$为它的积，记为

$$
\prod_{n=1}^{\infty}p_n = P 
$$

如果$\displaystyle \{P_n\}$发散或$\displaystyle \{P_n\}$收敛于0，则称无穷乘积$\displaystyle \{P_n\}$发散。

:::

::: {.callout-warning}
当 $\displaystyle \lim_{n \to \infty} P_n = 0$时，我们称无穷乘积$\displaystyle \prod_{n=1}^{\infty}p_n$发散于0，而不是收敛于0。
:::


这里就是很反直觉，如果一个数列收敛于0，我们称这个数列是收敛的；如果一个级数收敛于0呢？

级数是什么？如果有一个数列$\displaystyle a_1,a_2,a_3,\cdots,a_n,\cdots$,那么称$\displaystyle \{S_n=a_1+a_2+\cdots+a_n\}$为其部分和数列，而如果把$\displaystyle n \rightarrow \infty$,这时就出现了级数$\displaystyle \sum_{n=1}^{\infty}a_n$,如果一个级数收敛于0，比如说$\displaystyle \sum_{n=1}^{\infty}(-1)^{n+1}(\frac{1}{n})$，那对应的无穷乘积呢？也是趋于0，但是它不收敛，其中缘由要仔细考虑啊。


### 定理

::: {#thm-无穷乘积收敛对应的数项情况}

如果无穷乘积$\displaystyle \prod_{n=1}^{\infty}p_n$收敛，则

$$
\displaystyle \lim_{n \to \infty}p_n = 1;
$$ {#eq-first}

$$
\displaystyle \lim_{m \to \infty} \prod_{n=m+1}^{\infty}p_n = 1.
$$ {#eq-second}

:::

**证** &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;设$\displaystyle \prod_{n=1}^{\infty}p_n$的部分积数列为$\displaystyle \{P_n\}$，则

$$
p_n = \frac{P_{n+1}}{P_n}
$$

这时，两边取极限

$$
\lim_{n \to \infty}p_n = \lim_{n \to \infty}\frac{P_{n+1}}{P_n} = 1
$$

对于第二个(@eq-second)

$$
\prod_{n=m+1}^{\infty}p_n = \frac{\displaystyle \prod_{n=1}^{\infty}p_n}{P_m} = \frac{\displaystyle \prod_{n=1}^{\infty}p_n}{\displaystyle \prod_{n=1}^{m}p_n}
$$

两边对$\displaystyle m$取极限

$$
\lim_{m \to \infty}\prod_{n=m+1}^{\infty}p_n = \lim_{m \to \infty}\frac{\displaystyle \prod_{n=1}^{\infty}p_n}{\displaystyle \prod_{n=1}^{m}p_n} = 1
$$

::: {.callout-note}
我们常把$\displaystyle p_n$记为$\displaystyle 1+a_n$,则定理的第一个可表示为：如果无穷乘积$\displaystyle \prod_{n=1}^{\infty}a_n+1$收敛，则$\displaystyle \lim_{n \to \infty}a_n = 0$
:::

